[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libdrm",
  "expat",
  "fontconfig",
  "freetype",
  "mesa",
  "gtk3",
  "pango",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libxkbcommon"
]
